### PR TITLE
One typo fixed and one link added

### PR DESCRIPTION
**Pull request by bpcarter**
One typo fixed and one link added. Small test to see if I can edit. I have not worked in Github yet, but look forward to contributing to the docs.

### CODE REVIEW

**Comment by staroselskii** [comment]
Hello, @bpcarter! Thank you very much for taking your time and making a PR. Could you please take a look at our contributing [page](https://github.com/emlid/reachrs-docs/blob/master/contributing.md)? Just force push the change. It'll take a minute of your time.

**Comment by bpcarter** [comment]
@staroselskii , Would you like me to edit the description to follow the instructions on the contributing page? Or leave it as is and "force push"? If so, I do not know how to "force push"

**Comment by staroselskii** [comment]
@bpcarter 

Whatever you feel is easier for you. I propose closing this one and making a new PR off a new branch with a commit description that is compliant with our contribution rules. In case you have any questions, I'd be glad to help.

So basically what you need to do:

1) Click on a pen on the same page
2) Change the default branch name from patch-1 to something meaningful like `pr-fix-typos-in-tutorial`
3) Make the same changes as in this PR and add the title:
 "docs: common: tutorials: placing-base: fix small typos" 

with a description: 

"- One typo fixed and one link added"

4) Create a PR with this words: 

"Small test to see if I can edit. I have not worked in Github yet, but look forward to contributing to the docs."


As a sidenote: here's what I would do, if didn't want to create a new PR:

0) `git checkout` to my branch
1) `git fetch `- to get the latest changes in the repository
2) `git rebase -i origin/master` - to rebase my work
3) mark my commit to `e` that stands for edit
4) `git commit --amend` to change the commit description
5) `git rebase --continue`
6) `git push --force origin my-patch-1`

**Comment by TatianaAndreeva** [comment]
Hi @bpcarter,

Thanks for your contribution!

We've fixed it in our docs.

**Pull request closed without merging**
