### PR TITLE
docs: reach: common: rv: add v2.21 flashing guide for Edison-based Reach

### PR DESCRIPTION
**Pull request by TatianaAndreeva**

### CODE REVIEW

**Review by kobylyanskiy — COMMENTED** [review]
@TatianaAndreeva @staroselskii should we warn users here that their logs will be lost? Or we'll warn them in the post on community forum? I think it's better to duplicate.

**Comment by kobylyanskiy** [comment]
https://files.emlid.com/images/ReachImage_v2.21.0.zip - 404 :(

**Comment by kobylyanskiy** [comment]
md5sum should be updated as well. 
Image link: http://files.emlid.com/images/reach-rs-v2.21.0-dev.zip
bf3b0929a2e939f9af22a998d8644c51  deploy/reach-rs-v2.21.0-dev.zip
bf3b0929a2e939f9af22a998d8644c51  deploy/reach-rs-v2.21.0-dev.zip
Mender link:
2979309aa90c56acbdf892200c3d2504  deploy/reach-rs-v2.21.0-dev.mender

**Review by kobylyanskiy — CHANGES_REQUESTED** [review]
Please, update image link, md5 and warn about logs

**Comment by TatianaAndreeva** [comment]
I've fixed this, please take a look.

**Review by kobylyanskiy — APPROVED** [review]
LGTM

**Pull request merged**
